# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: 'fr'
    url_api_users: '%env(string:url_api_users)%'
    url_api_scryfall: '%env(string:url_api_scryfall)%'
    path_uploads: '%kernel.project_dir%/public/uploads'
    path_uploads_message_bug: '%kernel.project_dir%/public/uploads/message/bug'
    path_uploads_eligibilite_demande: '%kernel.project_dir%/public/uploads/eligibilite/demande'
    path_uploads_deviseur_derogation: '%kernel.project_dir%/public/uploads/deviseur/derogation'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    App\Listener\ImageCacheSubscriber:
        tags:
        - { name: doctrine.event_subscriber }
    App\Listener\LoginListener:
        tags:
        - { name: 'kernel.event_listener', event: 'security.interactive_login' }

fos_user:
    db_driver:      orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name:  main
    user_class:     App\Entity\User
    from_email:
        address: "no-reply@amediasolutions.fr"
        sender_name: "Amedia solutions"
    registration:
        confirmation:
            enabled: true
            template:   FOSUserBundle:Registration:email.txt.twig
            from_email:
                address:        "no-reply@amediasolutions.fr"
                sender_name:    "No Reply"
    service:
        mailer: fos_user.mailer.twig_swift
    resetting:
        email:
            template:   FOSUserBundle:Resetting:email.txt.twig